FROM golang:1.21-alpine
ARG CACHEBUST=1

ENV GO111MODULE=on
ENV GOPRIVATE=github.com/anhhuy1010
ENV APP_ENV development
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore


RUN apk add bash ca-certificates curl git gcc g++ libc-dev autoconf automake libtool make protoc
RUN mkdir -p /go/src/github.com/anhhuy1010/cms-user

# Install protoc
WORKDIR /go/src/github.com/anhhuy1010/cms-user
RUN go install github.com/golang/protobuf/protoc-gen-go@latest
RUN go install github.com/envoyproxy/protoc-gen-validate@latest
RUN mkdir -p /go/src/github.com/envoyproxy/protoc-gen-validate
RUN cp -r /go/pkg/mod/github.com/envoyproxy/protoc-gen-validate*/* /go/src/github.com/envoyproxy/protoc-gen-validate/.
ADD . .

RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN swag init ./controllers/*

RUN go install github.com/githubnemo/CompileDaemon@latest
ENTRYPOINT CompileDaemon -build="go build -o /tmp/cms-user ./main.go" -command="/tmp/cms-user"

